name: Deploy to DigitalOcean Droplet

# This workflow runs on a push to the 'master' branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy to DigitalOcean Droplet via SSH
      - name: Deploy with SSH and pull latest code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the correct directory

            # Stop nginx on the host after reboot
            sudo service nginx stop

            # Master branch
            cd /var/www/python_mvc
            
            # Run the deployment commands provided by the user

            # Make safe before pulling new code
            git stash

            # Git pull command by it's self
            git pull origin master


            # Allow acces through firewall
            sudo ufw allow 3000
            sudo ufw status

            # Set File and folder permissions
            #sudo chmod -R 755 /var/www/python_mvc

            # Stop docker
            docker-compose down

            # Start docker-compose
            docker-compose up -d --build
