name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH and pull latest code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo service nginx stop

            cd /var/www/python_mvc

            git stash
            git pull origin master

            sudo ufw allow 3000
            sudo ufw status

            docker-compose down

            # Ensure Dockerfile runs python-mvc with Gunicorn
            cat > Dockerfile <<'EOF'
            FROM python:3.11-slim
            WORKDIR /app
            COPY requirements.txt .
            RUN pip install --no-cache-dir -r requirements.txt
            COPY . .
            EXPOSE 3000
            CMD ["gunicorn", "--bind", "0.0.0.0:3000", "runserver:app"]
            EOF

            docker-compose up -d --build
