name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy via SSH
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            echo ">>> Switching to app directory"
            cd /var/www/python_mvc

            echo ">>> Stashing any local changes"
            git stash || true

            echo ">>> Pulling latest code from dev branch"
            git pull origin dev

            echo ">>> Allowing firewall ports (only once, safe if already set)"
            sudo ufw allow 80 || true
            sudo ufw allow 443 || true
            sudo ufw status

            echo ">>> Stopping old containers"
            docker-compose down

            echo ">>> Rebuilding & starting containers"
            docker-compose up -d --build

            echo ">>> Deployment finished successfully!"
