name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/python_mvc

            # Stop nginx on the host after reboot
            #sudo service nginx stop
            #sudo systemctl stop nginx

            git stash || true
            git pull origin dev

            sudo ufw allow 80
            sudo ufw allow 443
            sudo ufw allow 8080
            sudo ufw allow 8443
            sudo ufw allow 1000
            sudo ufw allow 2000
            sudo ufw status

            docker-compose down
            docker-compose up -d --build

            source venv/bin/activate
            gunicorn --bind 127.0.0.1:8000 wsgi:application
